export const SHOW_MODAL_STATUS = 'SHOW_MODAL_STATUS';

export const SET_MODAL_STATUS = 'SET_MODAL_STATUS';

export const ADD_OFFERS_FAVORITE = 'ADD_OFFERS_FAVORITE';

export const SHOW_OFFERS_FAVORITE = 'SHOW_OFFERS_FAVORITE';

export const REMOVE_OFFERS_FAVORITE = 'REMOVE_OFFERS_FAVORITE';